training:
  buildpack: python-train
  train: src.model:train
  model:
    path: data/models/model.ckpt
    upload_criteria: always
hosting:
  buildpack: python-websocket-api
  predict: src.model:predict
  model:
    path: data/models/model.ckpt